### ISSUE TITLE
Doesn't work in V-REP >= 3.1.3 

### ISSUE THREAD

**Issue by bergercookie** [mfueller/vrep_youbot_plugin#6]
Below is the message shown when trying to run the simulation in V-REP 3.3.0 Provided test files also don't work.

![screen shot 2016-02-21 at 18 08 42](https://cloud.githubusercontent.com/assets/5816719/13203751/0e653520-d8c7-11e5-930e-fa64a0952a83.png)

**Comment by sthoduka** [comment]
I am using 3.2.3 and get the same message. But it still works - so I am able to move the base, arm and gripper with the test scripts.
